AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket wiith environment tagging'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  S3BucketGithubActions:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionsTesting1
         

Outputs:
  BucketName:
    Description: 'Name of created S3 Bucket'
    Value: !Ref S3BucketGithubActions